name: ci

on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  checks-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements_dev.txt
      - run: make checks
      - run: make tests
