name: publish

on:
  push:
    branches:
      - master

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/jintonic
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install -r requirements_dev.txt
      - run: make build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
